name: flow
description: "High-performance, cross-platform music streaming client built with Flutter."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  palette_generator: ^0.3.3+3
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.0
  logger: ^2.4.0
  just_audio: ^0.9.40
  just_audio_windows: ^0.2.1
  just_audio_background: ^0.0.1-beta.13
  audio_service: ^0.18.14
  smtc_windows: ^0.1.1
  flutter_inappwebview: ^6.0.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  file_picker: ^11.0.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  youtube_explode_dart: ^3.0.5
  flutter_secure_storage: ^10.0.0
  dio: ^5.9.2
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
