name: flow
description: "High-performance, cross-platform music streaming client built with Flutter."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  palette_generator: ^0.3.3+3
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.0
  logger: ^2.4.0
  just_audio: ^0.9.40
  just_audio_windows: ^0.2.1
  just_audio_background: ^0.0.1-beta.13
  audio_service: ^0.18.14
  smtc_windows: 1.1.0
  flutter_inappwebview: ^6.0.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  file_picker: 8.1.7
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  youtube_explode_dart: ^3.0.5
  flutter_secure_storage: ^10.0.0
  dio: ^5.9.2
  crypto: ^3.0.7
  workmanager: ^0.9.0+3
  metadata_god: ^1.1.0
  drift: ^2.32.1
  sqlite3_flutter_libs: ^0.6.0+eol
  qr_flutter: ^4.1.0
  path: ^1.9.1
  window_manager: ^0.5.1
  spotify: ^0.16.1
  multicast_dns: ^0.3.3
  flutter_blue_plus: ^2.2.1
  mobile_scanner: ^7.2.0
  cryptography: ^2.9.0
  webview_flutter: 4.10.0
  ffmpeg_kit_flutter_new_full: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  drift_dev: ^2.32.1
  build_runner: ^2.15.0

dependency_overrides:
  flutter_rust_bridge: 2.11.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
